### ISSUE TITLE
Outdated forge causes spawnplacementregisterevent error

### ISSUE THREAD

**Issue by tyler26654** [iron431/Irons-Spells-n-Spellbooks#147]
I know I am using an old version of the mod but I tried every other version and all said the same thing so looking for help

Here is the Crash log, if there is anything else you may need I will send, sorry as well if I do not send all I don't normally run into issues:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-09-01 19:04:57
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.1.1-universal.jar%23231!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.1.1-universal.jar%23231!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,re:classloading,pl:mixin:APP:lod.mixins.json:MixinUtilBackgroudThread,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23226!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.1.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD irons_spellbooks --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/SpawnPlacementRegisterEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2385!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2385!/:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.1.jar%23227!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/b3ast/AppData/Roaming/.minecraft/mods/irons_spellbooks-1.19.2-1.1.3.jar
	Failure message: Iron's Spells 'n Spellbooks (irons_spellbooks) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/SpawnPlacementRegisterEvent
	Mod Version: 1.19.2-1.1.3
	Mod Issue URL: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.SpawnPlacementRegisterEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.1.jar%23228!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.1.jar%23227!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 400518008 bytes (381 MiB) / 1140850688 bytes (1088 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 35767.81
	Virtual memory used (MB): 21672.65
	Swap memory total (MB): 3073.71
	Swap memory used (MB): 110.35
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		TreeChop-1.19.2-forge-0.17.8al.jar                |HT's TreeChop                 |treechop                      |0.17.8a             |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDungeons-1.19.2-Forge-3.2.1.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.1  |COMMON_SET|Manifest: NOSIGNATURE
		open-parties-and-claims-forge-1.19.2-0.17.2.jar   |Open Parties and Claims       |openpartiesandclaims          |0.17.2              |COMMON_SET|Manifest: NOSIGNATURE
		spiderstpo-1.19.2-2.0.4.jar                       |Nyf's Spiders 2.0             |spiderstpo                    |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1013.jar                  |Just Enough Items             |jei                           |11.6.0.1013         |COMMON_SET|Manifest: NOSIGNATURE
		Laendli_1.7.4(for_1.19.2).jar                     |Laendli Transport             |laendli_transport             |1.7.4               |COMMON_SET|Manifest: NOSIGNATURE
		paragon-forge-3.0.2-1.19x.jar                     |Paragon                       |paragon                       |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.3.1.jar                 |Waystones                     |waystones                     |11.3.1              |COMMON_SET|Manifest: NOSIGNATURE
		Mimic-forge-1.19.1-1.2.38.jar                     |Mimic                         |mimic                         |1.2.38              |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.30.0_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.30.0              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		dustydecorations-1.0-1.19.2.jar                   |Dusty Decorations             |dustydecorations              |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.8.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.8  |COMMON_SET|Manifest: NOSIGNATURE
		lazydfu-1.0-1.19+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.1  |COMMON_SET|Manifest: NOSIGNATURE
		takesapillage-1.0.3-1.19.2.jar                    |It Takes A Pillage            |takesapillage                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		table_top_craft-1.19-3.1.2.jar                    |Table Top Craft               |table_top_craft               |1.19-3.1.2          |COMMON_SET|Manifest: NOSIGNATURE
		ManyIdeasHalloween-1.19.2-1.0.0.jar               |ManyIdeas Halloween           |manyideas_halloween           |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Orcz_0.85_1.19.2[PORT].jar                        |Orcz                          |orcz                          |0.82                |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.6.jar                       |Balm                          |balm                          |4.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.2-Forge-1.0.5  |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.1.1-universal.jar                 |Forge                         |forge                         |43.1.1              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.19.2-2.2.24.jar                 |Supplementaries               |supplementaries               |1.19.2-2.2.24       |COMMON_SET|Manifest: NOSIGNATURE
		AdvancementPlaques-1.19.2-1.4.7.jar               |Advancement Plaques           |advancementplaques            |1.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.1.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.1          |COMMON_SET|Manifest: NOSIGNATURE
		DistantHorizons-1.6.9a-1.19.2.jar                 |Distant Horizons              |lod                           |1.6.9a              |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.19.2-2.3.23.jar                 |Simple Voice Chat             |voicechat                     |1.19.2-2.3.23       |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.19.2-1.0.18.jar              |Sound Physics Remastered      |sound_physics_remastered      |1.19.2-1.0.18       |COMMON_SET|Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.3.jar                |More Villagers                |morevillagers                 |4.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.33-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.33       |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.12_mc1.19.2.jar          |Ambient Sounds                |ambientsounds                 |5.2.12              |COMMON_SET|Manifest: NOSIGNATURE
		bettercombat-forge-1.7.1+1.19.jar                 |Better Combat                 |bettercombat                  |1.7.1+1.19          |COMMON_SET|Manifest: NOSIGNATURE
		simpleshops-1.2.2.jar                             |Simple Shops                  |simpleshops                   |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		LetSleepingDogsLie-1.19.2-Forge-1.2.0.jar         |Let Sleeping Dogs Lie         |dogslie                       |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		firstperson-forge-2.2.3-mc1.19.2.jar              |FirstPersonModel Mod          |firstpersonmod                |2.2.3-mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.4_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |COMMON_SET|Manifest: NOSIGNATURE
		born_in_chaos_1.19_1.1.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		astikorcarts-1.19.2-1.1.2.jar                     |AstikorCarts                  |astikorcarts                  |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		Natural+Decoration+1.1.0.jar                      |Natural Decoration            |natural_decoration            |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.19.2-1.8.jar                      |betterfpsdist mod             |betterfpsdist                 |1.19.2-1.8          |COMMON_SET|Manifest: NOSIGNATURE
		ManyIdeasCore-1.19.2-1.3.0.jar                    |ManyIdeas Core                |manyideas_core                |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.1-mc1.19.1.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		L_Enders_Cataclysm-0.84-1.19.2.jar                |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.19.2-forge-1.0.49.jar                   |Iceberg                       |iceberg                       |1.0.49              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |COMMON_SET|Manifest: NOSIGNATURE
		Steam_Rails-1.19.2-1.1.1.jar                      |Create: Steam 'n Rails        |railways                      |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		tetra-1.19.2-5.4.0.jar                            |Tetra                         |tetra                         |5.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.19.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.19.2-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		workers-1.19.2-1.6.6.jar                          |Workers Mod                   |workers                       |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |COMMON_SET|Manifest: NOSIGNATURE
		ParCool-1.19.2-3.0.1.0-R.jar                      |ParCool!                      |parcool                       |1.19.2-3.0.1.0-R    |COMMON_SET|Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		irons_spellbooks-1.19.2-1.1.3.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.19.2-1.1.3        |ERROR     |Manifest: NOSIGNATURE
		backpacked-2.1.10-1.19.jar                        |Backpacked                    |backpacked                    |2.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		witherstormmod-1.19.2-3.1.1.1.jar                 |Cracker's Wither Storm Mod    |witherstormmod                |3.1.1.1             |COMMON_SET|Manifest: NOSIGNATURE
		effective_fg-1.3.4.jar                            |Effective (Forge)             |effective_fg                  |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |COMMON_SET|Manifest: NOSIGNATURE
		mutantmore-1.19.2-early-access-1.0.7.jar          |Mutant More                   |mutantmore                    |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		deeperdarker-forge-1.1.6-forge.jar                |Deeper and Darker             |deeperdarker                  |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.3.49-forge.jar                     |Architectury                  |architectury                  |6.3.49              |COMMON_SET|Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.6.6_mc1.19.2.jar              |ItemPhysic                    |itemphysic                    |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
		smallships-forge-1.19.2-2.0.0a2.2.jar             |Small Ships                   |smallships                    |2.0.0a2.2           |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		recruits-1.19.2-1.9.3.9.jar                       |Recruits Mod                  |recruits                      |1.9.3.9             |COMMON_SET|Manifest: NOSIGNATURE
		drinkbeer-refill-1.19.2-1.0.0.jar                 |Drink Beer Refill             |drinkbeer                     |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 21d98373-3e71-4871-a833-7f63569aa00f

**Comment by iron431** [comment]
you're using an ancient version of forge and a modestly outdated version of the mod. use the latest versions

**Comment by tyler26654** [comment]
shame, I was gonna use this mod on my server but I use vivecraft on the server and it only works with this version forge, thank you for the help
