### ISSUE TITLE
[Bug] Parsing error loading custom advancement

### ISSUE THREAD

**Issue by dennyun** [iron431/Irons-Spells-n-Spellbooks#250]
### Observed behaviour

**I'm having this problem when starting the server, how can I resolve this error?
version: irons_spellbooks-1.18.2-1.0.1**

```
[02:32:12] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement irons_spellbooks:irons_spellbooks/make_antiquated_compass_dupe: Expected item to be an item, was unknown string 'irons_spellbooks:antiquated_compass'

[02:32:13] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement irons_spellbooks:irons_spellbooks/magic_aura_dupe: Expected item to be an item, was unknown string 'irons_spellbooks:enchanted_ward_amulet'

[02:32:13] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement majruszsdifficulty:progressive_difficulty/warden_treasure_bag_16: Expected item to be an item, was unknown string 'majruszsdifficulty:warden_treasure_bag'

[02:32:13] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement irons_spellbooks:make_antiquated_compass: Expected item to be an item, was unknown string 'irons_spellbooks:antiquated_compass'

[02:32:13] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement majruszsdifficulty:progressive_difficulty/warden_treasure_bag: Expected item to be an item, was unknown string 'majruszsdifficulty:warden_treasure_bag'

[02:32:13] [Worker-Main-6/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement irons_spellbooks:magic_aura: Expected item to be an item, was unknown string 'irons_spellbooks:enchanted_ward_amulet'
```

**I tried to install the latest version and another error
version: irons_spellbooks-1.18.2-1.1.4.3**

```
[Worker-Main-3/ERROR] [minecraft/LootTables]: Couldn't parse loot table irons_spellbooks:chests/additional_ancient_city_loot
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'irons_spellbooks:ruined_book'
        at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:130) ~[?:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
        at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:130) ~[?:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:138) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[?:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2329!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[?:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:456) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[?:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2329!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2329!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[?:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:280) ~[?:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:277) ~[?:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.r
```

### Expected behaviour

May everything happen without any problems

### Steps to reproduce

1. install Magma to create the local server in version 1.18.2

2. generate the server data and then configure and install all the mods that will be executed including irons_spellbooks-1.18.2-1.0.1

3. start the server and the reported error will appear

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.18.2-1.0.1

### Forge version

Forge version: 40.2.10

**Comment by iron431** [comment]
Those aren't fatal issues, and we don't support 1.18.2, and we definitely don't support the non-latest update of any game version
