### ISSUE TITLE
[Bug] game crashing when reloading textures with Entity texture feature/entity texture model

### ISSUE THREAD

**Issue by LwkySad** [iron431/Irons-Spells-n-Spellbooks#288]
### Observed behaviour

I've been working on this modpack and reloading textures after retexturing irons spellsbook armors and everytime i reload it crashes

### Expected behaviour

the textures reload and update without crashing after i reload (f3+t)

### Steps to reproduce

1.install entity texture feature and model and irons spellsbook
2. modify a texture in the mod
3. reload textures on 1.20.1

### Server Type

Single Player

### Crashlog

<script src="https://gist.github.com/LwkySad/30ecfb20ae33e0535cc27e40bad85843.js"></script>

### Iron's Spells N Spellbooks version

1.20.1-2.2.1

### Forge version

1.20.1-latest

### Other mods

a bunch but they shouldnt matter here

**Comment by lab3** [comment]
Sorry. This doesn't look like it's us.  The crash report calls out several things you should chase down. 

```
Sinytra Connector: 1.0.0-beta.32+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
		Installed Fabric mods:

Suspected Mods: 
	Moonlight Library (moonlight), Version: 1.20-2.8.82
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		Mixin class: net.mehvahdjukaar.moonlight.core.mixins.DynamicTextureMixin
		Target: net.minecraft.client.renderer.texture.DynamicTexture
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.texture.DynamicTexture.wrapOperation$ejp000$moonlight$forceMipMap(DynamicTexture.java:540)

	Apoli (apoli), Version: 1.20.1-2.9.0.4
		Issue tracker URL: https://github.com/EdwinMindcraft/apoli/issues
		Mixin class: io.github.apace100.apoli.mixin.LivingEntityRendererMixin
		Target: net.minecraft.client.renderer.entity.LivingEntityRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.redirect$zfh000$apoli$preventFeatureRendering(LivingEntityRenderer.java:1099)

	Kelvin's Better Player Animations (betterplayeranimations), Version: 1.20.x-1.0.0
		Mixin class: net.dented.betterplayeranimations.mixin.PlayerEntityRendererMixin
		Target: net.minecraft.client.renderer.entity.player.PlayerRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$doh000$betterplayeranimations$render(PlayerRenderer.java:4074)

	Entity Texture Features (entity_texture_features), Version: 5.1.2
		Issue tracker URL: https://github.com/Traben-0/EmissiveMod/issues
		at TRANSFORMER/entity_texture_features@5.1.2/traben.entity_texture_features.utils.ETFUtils2.registerNativeImageToIdentifier(ETFUtils2.java:297)
		```
